### ISSUE TITLE
feature: Add commands for easier execution, instead of running code directly in lua

### ISSUE THREAD

**Issue by diegobit** [MisanthropicBit/decipher.nvim#20]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

The only way to use the plugin right after the install is to run it with lua, as shown in the video in the README, such as `:'<,'>lua require('decipher').encode_selection("base64")`. 

### Describe the solution you would like

It would be nice to have some commands, such as `:EncodeBase64`, `:EncodeCrockford`, etc.
This would also allow to start the plugin only when needed with the 'Cmd' feature of Lazy.

### Describe alternatives you have considered

Providing pre-made copy pastable mappings to put into the user config...

### Additional context

Right now I set the plugin like this, to have easier access to its features:
```
return {
  'MisanthropicBit/decipher.nvim',
  version = '*',
  event = 'VeryLazy',
  config = function()
    local decipher = require 'decipher'
    decipher.setup {
      vim.keymap.set({ 'n', 'v' }, '<leader>ube', function()
        decipher.encode_selection 'base64'
      end, { noremap = true, silent = true, desc = '[B]ase64 [E]ncode' }),
      vim.keymap.set({ 'n', 'v' }, '<leader>ubd', function()
        decipher.decode_selection 'base64'
      end, { noremap = true, silent = true, desc = '[B]ase64 [D]ecode' }),

      vim.keymap.set({ 'n', 'v' }, '<leader>ubse', function()
        decipher.encode_selection 'base64-url-safe'
      end, { noremap = true, silent = true, desc = '[B]ase64 URL [S]afe [E]ncode' }),
      vim.keymap.set({ 'n', 'v' }, '<leader>ubsd', function()
        decipher.decode_selection 'base64-url-safe'
      end, { noremap = true, silent = true, desc = '[B]ase64 URL [S]afe [D]ecode' }),

      vim.keymap.set({ 'n', 'v' }, '<leader>uue', function()
        decipher.encode_selection 'url'
      end, { noremap = true, silent = true, desc = '[U]RL [E]ncode' }),
      vim.keymap.set({ 'n', 'v' }, '<leader>uud', function()
        decipher.decode_selection 'url'
      end, { noremap = true, silent = true, desc = '[U]RL [D]ecode' }),
    }
  end,
}
```

Note: For anyone wondering, the `u` in `<leader>u`... stands for Utils

Thanks!

**Comment by MisanthropicBit** [comment]
Thanks for submitting an issue.

I actually originally included commands but [removed them](https://github.com/MisanthropicBit/decipher.nvim/commit/45b3a77194f275d8ea722373f526fe1449739d39) because it is so easy to add the mappings/commands that you want how you want and lessens the maintenance burden for me. Providing  `Encode`/`Decode` commands that use command completion for the codec would be slightly more involved for users though but a more future-proof solution than providing a command pair for each codec.

I'm also a bit worried that providing commands will ultimately just result in having duplicated ways to create the same mappings as I don't believe people will directly use the commands but just create mappings that use the commands/lua functions but feel free to discuss this further.

> This would also allow to start the plugin only when needed with the 'Cmd' feature of Lazy.

Fair point. I haven't measured and I don't use lazy but I would be surprised if this plugin has a high startup time.

> Providing pre-made copy pastable mappings to put into the user config...

I don't think I'll be adding this as the plugin already has quite a few ways to invoke a codec and I would hope the [documentation](https://github.com/MisanthropicBit/decipher.nvim/blob/master/doc/decipher.txt#L138-L262) is sufficient for helping users create the mappings they want (e.g. someone might want to invoke the `_prompt` variants, some might not...) but some examples might be useful?

**Comment by diegobit** [comment]
Thank you for the plugin and the thoughtful answer! If you need a beta tester for some feature, I can help!

> I actually originally included commands but removed them because it is so easy to add the mappings/commands that you want how you want and lessens the maintenance burden for me. Providing Encode/Decode commands that use command completion for the codec would be slightly more involved for users though but a more future-proof solution than providing a command pair for each codec.

That makes absolutely more sense, I agree.

> I'm also a bit worried that providing commands will ultimately just result in having duplicated ways to create the same mappings as I don't believe people will directly use the commands but just create mappings that use the commands/lua functions but feel free to discuss this further.

I'm rather new to the nvim/lua world, so I'm not 100% sure about this, but it seems to me that keymaps (when make sense, like nvim-surround, just to make an example) or commands are the two common ways to surface features to the user. To me, using lua directly seems a bit less clean, having to go "a level down". But again, I could not be seeing something... Maybe people just expects to run stuff with lua.

> Fair point. I haven't measured and I don't use lazy but I would be surprised if this plugin has a high startup time.

Well, of course, it's not much. Lazy's profiling says decipher takes 5ms on average. Also, by attaching it to the 'VeryLazy' event it should be loaded after everything else asynchronously. It's more a matter of really optimizing vim.

> I don't think I'll be adding this as the plugin already has quite a few ways to invoke a codec and I would hope the documentation is sufficient for helping users create the mappings they want [...] but some examples might be useful?

I agree. I also don't think there should be default mappings here.

> (e.g. someone might want to invoke the _prompt variants, some might not...)

Actually I read the docs but I missed the prompt variants 😅 Yes, I think the README would benefit with a short section summarizing the possible invocations, one or two example mappings...

**Comment by MisanthropicBit** [comment]
> Thank you for the plugin and the thoughtful answer! If you need a beta tester for some feature, I can help!

I'm glad you find it useful 🙂 and thanks for offering to beta test!

I have other plugins as well where adding predefined keymaps make sense but I personally prefer plugins to not define any keymaps by default since they can accidentally overwrite your own unless they check first.

I've used vim for around a decade before I moved to neovim and in vim-land it was more common to expose commands to users, specifically [`<Plug>`](https://neovim.io/doc/user/usr_41.html#using-%3CPlug%3E) mappings. I think most neovim users are used to just invoking lua functions by now but I can't know for sure. One thing is that commands provide an abstract layer if I wanted to change the underlying api.

> Yes, I think the README would benefit with a short section summarizing the possible invocations, one or two example mappings...

Agreed. I'll add this.

**Comment by MisanthropicBit** [comment]
@diegobit As I've used this plugin with changing needs and codebases, I've found that having commands might actually be very nice. Therefore I've implemented some in #37.

It looks like you're still [using `decipher`](https://github.com/diegobit/dotfiles/blob/main/.config/nvim/lua/plugins/decipher.lua) so this might still be relevant for you 🙂 You're welcome to try things out, otherwise I'll be merge it soon.

Also let me know if you need help with [these broken mappings](https://github.com/diegobit/dotfiles/blob/main/.config/nvim/lua/plugins/decipher.lua#L3-L15). They should work.

**Comment by diegobit** [comment]
Hey! Thanks for mentioning me!

I just tried a bunch of commands from the new branch and they all work :)

---

Since you are mentioning the broken mappings, I tried reenabling them again and they are still broken for me.

Steps:
- select a word
- do my `<leader>ce`, which executes `require('decipher').encode_selection_prompt { preview = true }`

Error I get:
```
Error executing vim.schedule lua callback: .../share/nvim/lazy/decipher.nvim/lua/decipher/ui/float.lua:275: 'height' key must be a positive Integer
stack traceback:
        [C]: in function 'nvim_win_set_config'
        .../share/nvim/lazy/decipher.nvim/lua/decipher/ui/float.lua:275: in function 'render_page'
        .../share/nvim/lazy/decipher.nvim/lua/decipher/ui/float.lua:407: in function 'switch_to_page'
        .../share/nvim/lazy/decipher.nvim/lua/decipher/ui/float.lua:538: in function 'open'
        ...ocal/share/nvim/lazy/decipher.nvim/lua/decipher/init.lua:87: in function 'open_float_handler'
        ...ocal/share/nvim/lazy/decipher.nvim/lua/decipher/init.lua:135: in function 'process_codec'
        ...ocal/share/nvim/lazy/decipher.nvim/lua/decipher/init.lua:151: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by MisanthropicBit** [comment]
> I just tried a bunch of commands from the new branch and they all work :)

Great 🙂 thanks for testing it out so quickly.

I cannot reproduce the issue with that mapping. Would you mind opening a new issue where you answer the questions below about the bug and fill out the template? Otherwise, it is fine to do here.

1. Could you bump to the most recent version and see if it persists? You're on 2.1.0 according to your `lazy-lock.json` and the latest is 3.0.0 (however the line you refer to makes it seem like you are not on 2.1.0).
2. Does this happen for any type of word? What word did you test on?
3. Is your terminal window very small by any chance?
4. Is it specifically the prompt + preview that doesn't work? Do the `encode_selection` + no preview work for you?

It looks like there is some calculation with the height of the floating window that gets truncated to zero [here](https://github.com/MisanthropicBit/decipher.nvim/blob/ba9ae0c198d6002f90dd7a509d13e91f96afe986/lua/decipher/ui/float.lua#L247).

**Comment by diegobit** [comment]
Thank you!
Done #38 

While writing the issue I noticed it worked with a clean init.lua, so I tried a bunch of things and noticed it's an interaction with telescope-ui-select. Since we are here, I wrote everything, but I'm not sure if the bug is in telescope then.

As for your questions, for completeness:
1. I was in add-commands branch
2. yes, any
3. no
4. also without preview. Without preview simply nothing happens
  4b. but if i had a previosly saved selection (visual mode, select, back to normal), then the previous word gets encoded (preview works with previous word)
